import { ChainConfig, MULTICALL3_ADDRESS } from '@cvh/types';

const NULL_CONTRACTS = {
  walletFactoryAddress: null,
  forwarderFactoryAddress: null,
  walletImplementationAddress: null,
  forwarderImplementationAddress: null,
  multicall3Address: MULTICALL3_ADDRESS,
};

export const DEFAULT_CHAINS: Record<number, ChainConfig> = {
  1: {
    chainId: 1,
    name: 'Ethereum Mainnet',
    shortName: 'eth',
    nativeCurrency: { symbol: 'ETH', decimals: 18 },
    rpcEndpoints: [],
    blockTimeSeconds: 12,
    confirmationsDefault: 12,
    contracts: { ...NULL_CONTRACTS },
    explorerUrl: 'https://etherscan.io',
    gasPriceStrategy: 'eip1559',
    isActive: true,
    isTestnet: false,
  },
  56: {
    chainId: 56,
    name: 'BNB Smart Chain',
    shortName: 'bnb',
    nativeCurrency: { symbol: 'BNB', decimals: 18 },
    rpcEndpoints: [],
    blockTimeSeconds: 3,
    confirmationsDefault: 20,
    contracts: { ...NULL_CONTRACTS },
    explorerUrl: 'https://bscscan.com',
    gasPriceStrategy: 'legacy',
    isActive: true,
    isTestnet: false,
  },
  137: {
    chainId: 137,
    name: 'Polygon Mainnet',
    shortName: 'matic',
    nativeCurrency: { symbol: 'MATIC', decimals: 18 },
    rpcEndpoints: [],
    blockTimeSeconds: 2,
    confirmationsDefault: 30,
    contracts: { ...NULL_CONTRACTS },
    explorerUrl: 'https://polygonscan.com',
    gasPriceStrategy: 'eip1559',
    isActive: true,
    isTestnet: false,
  },
  42161: {
    chainId: 42161,
    name: 'Arbitrum One',
    shortName: 'arb1',
    nativeCurrency: { symbol: 'ETH', decimals: 18 },
    rpcEndpoints: [],
    blockTimeSeconds: 1,
    confirmationsDefault: 20,
    contracts: { ...NULL_CONTRACTS },
    explorerUrl: 'https://arbiscan.io',
    gasPriceStrategy: 'eip1559',
    isActive: true,
    isTestnet: false,
  },
  10: {
    chainId: 10,
    name: 'OP Mainnet',
    shortName: 'oeth',
    nativeCurrency: { symbol: 'ETH', decimals: 18 },
    rpcEndpoints: [],
    blockTimeSeconds: 2,
    confirmationsDefault: 20,
    contracts: { ...NULL_CONTRACTS },
    explorerUrl: 'https://optimistic.etherscan.io',
    gasPriceStrategy: 'eip1559',
    isActive: true,
    isTestnet: false,
  },
  43114: {
    chainId: 43114,
    name: 'Avalanche C-Chain',
    shortName: 'avax',
    nativeCurrency: { symbol: 'AVAX', decimals: 18 },
    rpcEndpoints: [],
    blockTimeSeconds: 2,
    confirmationsDefault: 20,
    contracts: { ...NULL_CONTRACTS },
    explorerUrl: 'https://snowtrace.io',
    gasPriceStrategy: 'eip1559',
    isActive: true,
    isTestnet: false,
  },
  8453: {
    chainId: 8453,
    name: 'Base',
    shortName: 'base',
    nativeCurrency: { symbol: 'ETH', decimals: 18 },
    rpcEndpoints: [],
    blockTimeSeconds: 2,
    confirmationsDefault: 20,
    contracts: { ...NULL_CONTRACTS },
    explorerUrl: 'https://basescan.org',
    gasPriceStrategy: 'eip1559',
    isActive: true,
    isTestnet: false,
  },
};
