USE `cvh_transactions`;

CREATE TABLE IF NOT EXISTS `flush_operations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `operation_uid` VARCHAR(255) NOT NULL,
  `client_id` BIGINT NOT NULL,
  `project_id` BIGINT NOT NULL,
  `chain_id` INT NOT NULL,
  `operation_type` ENUM('flush_tokens','sweep_native') NOT NULL,
  `mode` ENUM('manual','automated','batch') NOT NULL DEFAULT 'manual',
  `trigger_type` ENUM('user','system','scheduled') NOT NULL,
  `triggered_by` BIGINT NULL,
  `is_dry_run` TINYINT(1) NOT NULL DEFAULT 0,
  `status` ENUM('pending','queued','processing','succeeded','failed','partially_succeeded','canceled') NOT NULL DEFAULT 'pending',
  `token_id` BIGINT NULL,
  `wallet_id` BIGINT NOT NULL,
  `total_addresses` INT NOT NULL DEFAULT 0,
  `succeeded_count` INT NOT NULL DEFAULT 0,
  `failed_count` INT NOT NULL DEFAULT 0,
  `total_amount` DECIMAL(78,0) NOT NULL DEFAULT 0,
  `succeeded_amount` DECIMAL(78,0) NOT NULL DEFAULT 0,
  `gas_cost_total` DECIMAL(78,0) NOT NULL DEFAULT 0,
  `tx_hash` VARCHAR(66) NULL,
  `batch_tx_hashes` JSON NULL,
  `error_message` TEXT NULL,
  `dry_run_result` JSON NULL,
  `filters_applied` JSON NULL,
  `started_at` DATETIME(3) NULL,
  `completed_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_operation_uid` (`operation_uid`),
  INDEX `idx_client_project` (`client_id`, `project_id`, `status`, `created_at`),
  INDEX `idx_chain_type` (`chain_id`, `operation_type`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `flush_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `operation_id` BIGINT NOT NULL,
  `deposit_address_id` BIGINT NOT NULL,
  `address` VARCHAR(42) NOT NULL,
  `status` ENUM('pending','processing','succeeded','failed','skipped') NOT NULL DEFAULT 'pending',
  `token_id` BIGINT NULL,
  `amount_before` DECIMAL(78,0) NULL,
  `amount_flushed` DECIMAL(78,0) NULL,
  `tx_hash` VARCHAR(66) NULL,
  `gas_cost` DECIMAL(78,0) NULL,
  `error_message` TEXT NULL,
  `processed_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_operation` (`operation_id`, `status`),
  INDEX `idx_address` (`deposit_address_id`),
  CONSTRAINT `fk_items_operation` FOREIGN KEY (`operation_id`) REFERENCES `flush_operations` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
