'use client';
import { useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { X, AlertTriangle } from 'lucide-react';
import { GasTank, gasTanksApi } from '@/lib/api';

interface Props { tank: GasTank; onClose: () => void; }

export function ExportKeystoreModal({ tank, onClose }: Props) {
  const [step, setStep] = useState<1 | 2>(1);
  const [mnemonic, setMnemonic] = useState('');
  const [password, setPassword] = useState('');

  const mut = useMutation({
    mutationFn: () => gasTanksApi.exportKeystore(tank.chainId, { mnemonic: mnemonic.trim(), password }),
    onSuccess: (res) => {
      const blob = new Blob([JSON.stringify(res.keystore, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `gas-tank-${tank.chainId}-${tank.address.slice(0, 10)}.json`;
      a.click();
      URL.revokeObjectURL(url);
      setMnemonic(''); setPassword('');
      onClose();
    },
  });

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4" onClick={onClose}>
      <div className="w-full max-w-md rounded-2xl border border-white/10 bg-zinc-900 p-6 space-y-4" onClick={(e) => e.stopPropagation()}>
        <header className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Export Keystore — {tank.chainName}</h2>
          <button onClick={onClose} aria-label="Close"><X className="h-5 w-5 text-zinc-400" /></button>
        </header>

        {step === 1 && (
          <>
            <div className="rounded-lg border border-yellow-500/30 bg-yellow-500/10 p-3 text-sm">
              <div className="flex items-center gap-2 font-medium text-yellow-300">
                <AlertTriangle className="h-4 w-4" /> Security notice
              </div>
              <p className="mt-2 text-zinc-300">
                The keystore is generated by the server from your mnemonic. Your mnemonic is sent over TLS,
                used in-memory only, and is <strong>never stored or logged</strong>. The endpoint is
                rate-limited and audit-logged. The downloaded JSON is encrypted with the password you choose.
              </p>
            </div>
            <div className="flex justify-end">
              <button onClick={() => setStep(2)} className="rounded-md bg-blue-600 px-3 py-2 text-sm hover:bg-blue-500">
                I understand, continue
              </button>
            </div>
          </>
        )}

        {step === 2 && (
          <>
            <label className="block text-xs text-zinc-500 mt-1">Project mnemonic</label>
            <textarea value={mnemonic} onChange={(e) => setMnemonic(e.target.value)} rows={3}
                      autoComplete="off" spellCheck={false}
                      className="w-full rounded-md bg-zinc-800 px-3 py-2 font-mono text-sm text-white" />
            <label className="block text-xs text-zinc-500">Keystore password (≥ 8 chars)</label>
            <input type="password" value={password} onChange={(e) => setPassword(e.target.value)}
                   className="w-full rounded-md bg-zinc-800 px-3 py-2 text-sm text-white" />
            {mut.error && <p className="text-sm text-red-400">{(mut.error as Error).message}</p>}
            <div className="flex justify-end gap-2">
              <button onClick={() => setStep(1)} className="rounded-md px-3 py-2 text-sm hover:bg-white/5">Back</button>
              <button onClick={() => mut.mutate()}
                      disabled={mut.isPending || mnemonic.split(/\s+/).filter(Boolean).length < 12 || password.length < 8}
                      className="rounded-md bg-blue-600 px-3 py-2 text-sm hover:bg-blue-500 disabled:opacity-50">
                {mut.isPending ? 'Encrypting…' : 'Download keystore'}
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
