/**
 * Mock for generated PrismaClient used in unit tests.
 * The real PrismaClient is generated by Prisma and extends from the generated output.
 * This mock provides a minimal stub so PrismaService can extend it without
 * requiring a real database connection.
 */
export class PrismaClient {
  $connect = jest.fn();
  $disconnect = jest.fn();
}
